name: test

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  PYTHON_VERSION: 3.10.11

jobs:
  test:
    runs-on: windows-2022
    steps:

      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: build dll
        run: |
          external/Texconv-Custom-DLL/batch_files/build_without_vcruntime.bat
          cp external/Texconv-Custom-DLL/texconv.dll src/directx

      - name: Set up Python v${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install pytest
        run: pip install flake8 codespell pytest pytest-cov

      - name: Linting
        run: |
          flake8
          codespell

      - name: Test
        env:
          PYTHONPATH: ${{ github.workspace }}\src
        run: pytest tests -svv --cov=src
